### ISSUE TITLE
Cannot resize whole table and column resize

### ISSUE THREAD

**Issue by mesb1** [MymsMan/vbox_webif#1]
Hi.

Using latest available version from github (09.08.2021).

Disabled couple of columns like Ser id and Rec id.
The whole epg table becomes slightly thinner.
And there is no way to increase width of the whole table. (or i am not quite understand how)

Problem is that i want to make description column a little wider, but when i am doing it, my Action column hiding under right side of whole table.
If there is no possibility to resize whole table, i think resize should be more accurate.

**Comment by MymsMan** [comment]
I have checked in a change to resize the grid  to window size whenever an column is hidden/shown, also to maintain  table width when column width is changed

Hope it solves your issues

**Comment by mesb1** [comment]
Hi.
Looks like now it is fine.
Thanks!
